// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxBrhPM4H5OIQjlO55GXh6SBc2IDuUBQ',
    appId: '1:908404234962:web:e4e4e120cdbfbfd31eab0b',
    messagingSenderId: '908404234962',
    projectId: 'mychatapp19-b8ae7',
    authDomain: 'mychatapp19-b8ae7.firebaseapp.com',
    storageBucket: 'mychatapp19-b8ae7.appspot.com',
    measurementId: 'G-78Q4NN1YNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFqMnTQgrL2wpAkV76qS9R1TRAHHE1OUg',
    appId: '1:908404234962:android:8f59733b75c706e11eab0b',
    messagingSenderId: '908404234962',
    projectId: 'mychatapp19-b8ae7',
    storageBucket: 'mychatapp19-b8ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47FROAzRP7I4k1Naa1leBBuMfnaboQhI',
    appId: '1:908404234962:ios:0fa415f18309a9601eab0b',
    messagingSenderId: '908404234962',
    projectId: 'mychatapp19-b8ae7',
    storageBucket: 'mychatapp19-b8ae7.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47FROAzRP7I4k1Naa1leBBuMfnaboQhI',
    appId: '1:908404234962:ios:0fa415f18309a9601eab0b',
    messagingSenderId: '908404234962',
    projectId: 'mychatapp19-b8ae7',
    storageBucket: 'mychatapp19-b8ae7.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZxBrhPM4H5OIQjlO55GXh6SBc2IDuUBQ',
    appId: '1:908404234962:web:5aa91c9d9bcdd3871eab0b',
    messagingSenderId: '908404234962',
    projectId: 'mychatapp19-b8ae7',
    authDomain: 'mychatapp19-b8ae7.firebaseapp.com',
    storageBucket: 'mychatapp19-b8ae7.appspot.com',
    measurementId: 'G-8DQNRGXRPJ',
  );
}
